### ISSUE TITLE
Do not clear screen on launch

### ISSUE THREAD

**Issue by hauleth** [joshuaclayton/unused#102]
This provide bad UI in my opinion and screws with terminal scroll back. It also can hide important informations for the user.

**Comment by ip1981** [comment]
Related: https://github.com/joshuaclayton/unused/issues/105

**Comment by pawamoy** [comment]
I would add: do not clear screen **at all**. Look at that:

```console
pawamoy@corsair aria2p (master) $ docker run --rm -it -v $(pwd):/code joshuaclayton/unused unused

Unused: analyzing 387 terms

Calculating cache fingerprint... 























Unused: analyzing 387 terms

Working [============================================>] 100%

















































Unused found no results
pawamoy@corsair aria2p (master) $
```

**Comment by joshuaclayton** [comment]
Noted; thanks for highlighting this. I'm almost done with a rewrite in Rust, and new behavior does not clear the screen. Closing this out as I won't be addressing this in this version specifically.
