### ISSUE TITLE
Is it possible to improve the performance of unused?

### ISSUE THREAD

**Issue by mrageh** [joshuaclayton/unused#103]
Not the usual issue to be opened in a project that works really well. But I was wondering if it would be possible to improve the performance of Unused on large codebases. It can take a long time on large codebases which makes it difficult to run on those codebases on a regular basis.

**Comment by ip1981** [comment]
Maybe not related, but I'd stop using and cut off dependencies on terminal packages like `terminal-progress-bar`. They are causing a lot of troubles when building. Old good plain output to stdout would be just fine.

**Comment by joshuaclayton** [comment]
@mrageh yes, definitely! Right now, there's a caching mechanism that effectively snapshots the entire structure of the codebase in a SHA, and uses that as a look-up to responses. If you run unused once, don't change any tracked files, and run it again, it *should* be retrieving the cached results and serving those, resulting in near-instantaneous results.

In theory, unused could build smaller snapshots at certain levels deep, and read from those caches as well, resulting in partial recalculation (not across the entire codebase).

@mrageh is this something you'd be interested in taking on? If so, I'd be happy to outline where this fits together!

**Comment by joshuaclayton** [comment]
@mrageh I've been working on a complete rewrite of Unused in Rust. With the newest changes, it takes what was previously 20+ minutes long to under five seconds. I'll close this out for now as I won't be addressing speed within this version of the codebase.
