### ISSUE TITLE
Dependencies are painful

### ISSUE THREAD

**Issue by ip1981** [joshuaclayton/unused#105]
I'd stop using and cut off dependencies on terminal packages like `terminal-progress-bar`. They are causing a lot of troubles when building. Old good plain output to stdout would be just fine.

Look, you depend on `terminal-progress-bar >= 0.1.1.1 && < 0.1.2` this is already a sign of problems.

Various combinations of GHC, HUnit, etc. are very fragile, while aren't needed for the main purpose of Unused.

P. S. Stack is not an answer.

**Comment by aldrienht** [comment]
@ip1981 getting same error installing.

`stack install unused`

`Error: While constructing the build plan, the following exceptions were encountered:`

In the dependencies for unused-0.9.0.0:
    `terminal-progress-bar must match >=0.1.1.1 && <0.1.2`, but the stack configuration has no specified version  (latest matching version is 0.1.1.1)
needed since unused is a build target.

any temporary fix?

**Comment by ip1981** [comment]
@aldrienht I think you could use this repository and `stack.yaml` in it to build `unused`. `stack.yaml` pins `terminal-progress-bar`.

**Comment by joshuaclayton** [comment]
@ip1981 @aldrienht I've released 0.10.0.0, which attempts to address this; mind trying to update unused and see if it can be done via Homebrew? (It should also be fixed using stack)
