### ISSUE TITLE
Generating clean ASCII-only report

### ISSUE THREAD

**Issue by ShockwaveNN** [joshuaclayton/unused#108]
By default report generated by `unused` command include progress log and color symbols, so command like this:
`unused > unused.log`
result in pretty unreadeble reports that looks like this:
![image](https://user-images.githubusercontent.com/668524/77776204-b5598100-705e-11ea-9940-f9c4b4e4b18e.png)

Is there an option to generate just ASCII-code reports? Or any kind of custom formatter support?

**Comment by joshuaclayton** [comment]
Hi @ShockwaveNN, I'm rewriting Unused in Rust. In addition to being more performant, I've introduced a flag to allow for disabling of color output because of this issue you'd highlighted here. Since I won't be addressing it within this repo, I'm going to close this issue out.

**Comment by ShockwaveNN** [comment]
OK, thank you. Is rust version will be at another repo?

**Comment by joshuaclayton** [comment]
@ShockwaveNN yes, it's in a separate repo, to be hosted under this org: https://github.com/unused-code, in private alpha now
