### ISSUE TITLE
RSpec's fanciness confuses unused

### ISSUE THREAD

**Issue by r00k** [joshuaclayton/unused#19]
I have a bunch of methods on page objects like `visible?` and `has_modal?`.

Thanks to RSpec being fancy, we call them with `be_visible` and `have_modal`.

This makes `unused` think they are unused, but they ain't.

**Comment by joshuaclayton** [comment]
@r00k do you have any opinions as to whether these should be visually grouped when printing results, or if unused should just perform the correct counts?

**Comment by joshuaclayton** [comment]
@r00k an example might be:

```
be_completed|completed?
     be_completed|completed?   4,  8  app/models/todo.rb                                      used frequently
     be_completed|completed?   4,  8  app/views/todos/index.html.erb                          used frequently
     be_completed|completed?   4,  8  spec/models/todo_spec.rb                                used frequently
     be_completed|completed?   4,  8  spec/models/todo_spec.rb                                used frequently
```

vs

```
be_completed
     be_completed             4,  8  spec/models/todo_spec.rb                                used frequently

...

completed?
     completed?               4,  8  app/models/todo.rb                                      used frequently
     completed?               4,  8  app/views/todos/index.html.erb                          used frequently
     completed?               4,  8  spec/models/todo_spec.rb                                used frequently
```

**Comment by joshuaclayton** [comment]
In both cases, the count and relationship between data is there (four files, eight occurrences), and it calculates likelihood correctly based on that.

**Comment by joshuaclayton** [comment]
Initial PR: https://github.com/joshuaclayton/unused/pull/43

**Comment by joshuaclayton** [comment]
My personal preference is to leave the names the same, but have the calculations reflect the likelihood (second version). Less of the code needs to change in the second version too.

**Comment by r00k** [comment]
No strong feelings on the issue. :)

On Sun, May 29, 2016 at 1:35 PM, Josh Clayton <notifications@github.com>
wrote:

> My personal preference is to leave the names the same, but have the
> calculations reflect the likelihood (second version). Less of the code
> needs to change in the second version too.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joshuaclayton/unused/issues/19#issuecomment-222372601>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAC2VeK-xz9B6GIkptsG6Lasc1B9zdGTks5qGc5PgaJpZM4IdMUJ>
> .
>



-- 
-Ben
