### ISSUE TITLE
Unable to run on OS X El Capitan (10.11.5)

### ISSUE THREAD

**Issue by itsmeduncan** [joshuaclayton/unused#52]
[Following the directions here](https://github.com/jollygoodcode/jollygoodcode.github.io/issues/20) when I run `cat .tags | unused --stdin` I get the following:

```
$ cat .tags | unused --stdin

Unused: analyzing 384 terms

Calculating cache fingerprint... 
find: fts_read: Invalid argument
unused: readCreateProcess: find "." "-type" "f" "-not" "-path" "*/.git/*" "-not" "-name" "*/.byebug_history" "-not" "-path" "*/.byebug_history/*" "-not" "-name" "*/.env" "-not" "-path" "*/.env/*" "-not" "-name" "*/.envrc" "-not" "-path" "*/.envrc/*" "-not" "-name" "*/.powenv" "-not" "-path" "*/.powenv/*" "-not" "-name" "*/.rspec" "-not" "-path" "*/.rspec/*" "-not" "-name" "*/.rvmrc" "-not" "-path" "*/.rvmrc/*" "-not" "-name" "*/.bundle" "-not" "-path" "*/.bundle/*" "-not" "-path" "*/bower_components/*" "-not" "-path" "*/coverage/*" "-not" "-path" "*/db/*.sqlite3" "-not" "-path" "*/db/*.sqlite3-journal" "-not" "-name" "*/log" "-not" "-path" "*/log/*" "-not" "-path" "*/log/*" "-not" "-path" "*/node_modules/*" "-not" "-name" "*/public/system" "-not" "-path" "*/public/system/*" "-not" "-name" "*/spec/tmp" "-not" "-path" "*/spec/tmp/*" "-not" "-name" "*/tmp" "-not" "-path" "*/tmp/*" "-not" "-name" "*/vendor/bundle" "-not" "-path" "*/vendor/bundle/*" "-not" "-path" "*/capybara-*.html" "-not" "-path" "*/pickle-email-*.html" "-not" "-name" "*/rerun.txt" "-not" "-path" "*/rerun.txt/*" "-not" "-path" "*/public/uploads/**/*" "-exec" "/sbin/md5" "{}" "+" (exit 1): failed
```

**Environment**

```
$ brew info unused
joshuaclayton/formulae/unused: stable 0.5.0.2, HEAD
A command line tool to identify unused code.
https://github.com/joshuaclayton/unused
/usr/local/Cellar/unused/0.5.0.2 (7 files, 24.9M) *
  Built from source on 2016-06-30 at 14:30:07
From: https://github.com/joshuaclayton/homebrew-formulae/blob/master/Formula/unused.rb
==> Dependencies
Build: ghc ✔, cabal-install ✔, ag ✔
```

```
$ which ctags
ctags: aliased to /usr/local/bin/ctags

$ ctags --version
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 13 2015, 03:28:50
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

```
$ zsh --version
zsh 5.2 (x86_64-apple-darwin15.0.0)
```

Let me know how else I can provide info!

**Comment by joshuaclayton** [comment]
@itsmeduncan sorry to hear about that! Internally, `unused` reads your `.gitignore` file and, with `find` and `md5`, generates a fingerprint to cache the results, resulting in significantly faster calculation when the codebase doesn't change.

Since it's failing on `find` on what might be a permissions thing, it might be good to verify ownership of all the directories in your project to make sure they're set correctly.

Additionally, can you paste the entire contents of your `.gitignore` file, which is used to generate the `find` command it's failing on?

In the meantime, you should be able to run `unused` as such:

```sh
cat .tags | unused --stdin -C
```

The `-C` flag disables the cache, which should help for the time being.

**Comment by itsmeduncan** [comment]
@joshuaclayton Awesome, `cat .tags | unused --stdin -C` works for now. Will dig into the permissions. Awesome project!

**Comment by joshuaclayton** [comment]
@itsmeduncan Any luck with permissions? I *believe* `find . -type f -not -perm -u+r` from within the root of the app should find everything your user can't read, which may help.

**Comment by itsmeduncan** [comment]
@joshuaclayton It looks like the standard `cat .tags | unused --stdin` command works in the latest version of `unused`. I haven't had a chance to look into by the supplied find (`find . -type f -not -perm -u+r`) doesn't return anything meaning it wasn't permissions. This should be close-able from my perspective. Thanks!

**Comment by joshuaclayton** [comment]
@itsmeduncan that's great news - thanks for the heads up!
