### ISSUE TITLE
Getting `Argument list too long` error

### ISSUE THREAD

**Issue by dmagliola** [joshuaclayton/unused#63]
Running on my codebase, I get this output:

```
Unused: analyzing 8594 terms
Working [=========================================>...]  92%unused: ag: readCreateProcessWithExitCode: runInteractiveProcess: exec: resource exhausted (Argument list too long)
```

Not sure how to get more debug info, or anything that'd let me know where / why it's failing.

Any pointers?

**Comment by joshuaclayton** [comment]
@dmagliola apologies on the late reply; I wasn't receiving notifications of issues being created.

Is there a way you could share your tags file with me, either publicly or privately? It looks like the command being sent to `ag` is much too long, which to me signifies that it's a problem with the token. If it's possible to send along `cat .git/tags | cut -f1 | uniq` (adjusting to wherever your tags file exists), that might help, but `cut` may not identify the first field correctly.

What we're really looking for is either:

1. an overly long tag name, or
2. a tag name that somehow has a bunch of spaces in it

Looking forward to seeing what you're able to find!

**Comment by joshuaclayton** [comment]
@dmagliola I'm going to close this for now, due to inactivity; let me know if I can help in any way.

**Comment by srt32** [comment]
I'm getting the same error:

`(Argument list too long)`

and looking at tags:

`cat tmp/tags  | cut -f1 | uniq`

I see some very long ones relating to `jasmine` (from full stack Rails app):

```
jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.jasmine.ja
<snip>
```

Perhaps there is a way to exclude very long tags?
