### ISSUE TITLE
Create a sample directory for frameworks

### ISSUE THREAD

**Issue by jvanbaarsen** [joshuaclayton/unused#66]
First of all, amazing tool!

Would it make sense to create a sample directory where you can find an `unused.yml` file for your framework? For example in Ruby on Rails where the schema.rb file is excluded etc?

If so, I would gladly help with the Ruby on Rails one (The other frameworks I don't use so that becomes harder for me).

**Comment by joshuaclayton** [comment]
@jvanbaarsen this actually brings up an interesting point - I think for things where it applies across all Rails apps (so, not specific to e.g. Pundit, Devise, or JSONAPI::Resources), it should go in the default configuration, which can be found [here](https://github.com/joshuaclayton/unused/blob/master/data/config.yml).

Maybe for more community-driven or configs that deviate from Rails a bit (e.g. the examples above), either a) links to a few good `unused.yml` files from peoples' dotfiles repos, or b) a new directory `doc/unused.yml/examples/` where community-maintained examples exist.

**Comment by jvanbaarsen** [comment]
@joshuaclayton Ok great! In that case I'll add some of my findings to the default config! I'll close this issue for now.
