### ISSUE TITLE
Unused gets killed before finishing

### ISSUE THREAD

**Issue by pecavalheiro** [joshuaclayton/unused#77]
Hi guys,

I'm trying to use Unused in a Ruby/Rails project, but it can't finish the analysis. This is the output:

```
Unused: analyzing 41740 terms

Working [======================================>......]  85%Killed
```

It always gets killed around 85%. 
I think there may some issues with cpu or ram consumption, but I'm not sure how to debug it. 
Is there any --verbose or --debug flag?

I'm running Debian on a i7 8gb ram, more than enough to handle such analysis...

Thanks!

**Comment by joshuaclayton** [comment]
@pecavalheiro there's currently no verbose/debug flag. Could you run `htop` (you may need to install it) to understand whether it's CPU/RAM usage first?

Additionally, if possible could you share the generated ctags file, or take a look around that spot in the file (maybe line 36,000 - 37,000) to see if anything looks "off" (either odd characters, really long lines, or anything else out of the norm)?

Finally, would anything be killing `ag` processes? `unused` leverages it behind the scenes to find the tokens.

**Comment by pecavalheiro** [comment]
My project got updated, and this issue has gone. It was probably caused by some odd character or long line, as you said. If it happens again, I'll take a detailed look and report to you. 

Thank you! :smile:
