### ISSUE TITLE
Using in CI?

### ISSUE THREAD

**Issue by andyw8** [joshuaclayton/unused#81]
@joshuaclayton 

I wondered if you've had considered if Unused would be suitable to run as part of a CI setup? It's perhaps too slow to run for every commit, but I guess it could be scheduled to run overnight against a project's master branch.

**Comment by joshuaclayton** [comment]
@andyw8 I've had some initial conversations with @pbrisbin from CodeClimate about a formatter and other machinery there, but that's the extent of my research thus far. I do think an automated, repeatable process for identifying recently introduced unused methods is compelling and could see the value.

Tangentially related, I'd like to speed this up to a point where it *could* be run at a higher frequency, especially on large codebases (which are oftentimes the ones with more unused code/code rot in general anyway).

**Comment by andyw8** [comment]
Thanks for the response. I would love to have this available through Code Climate some day.
