### ISSUE TITLE
No results using on Odoo modules

### ISSUE THREAD

**Issue by NicolasWebDev** [joshuaclayton/unused#84]
I am trying to use unused on my custom odoo modules, written in Python.

It does not find any results. For testing, I added a method called "nstntsasrnitenetiu", it does not detect it as not being used either.

My directory structure is like:
```
dir1/                                                                             
├── dir2                                                                          
│   ├── module1                                                                   
│   ├── module2                                                                   
│   ├── module3                                                                   
│   ├── module4                                                                   
│   ├── module5                                                                   
│   └── tags                                                                      
└── .gitignore                                                                    
```
dir2 is in the .gitignore, so all of my modules are ignored.

ctags seems to create the tags successfully, with more than 37K tokens found.

I have also tried unused on a ruby project of mine, and there it works fine.

EDIT: now that I am thinking about it, dir2 is a bazaar repo. Could it be the problem?

**Comment by joshuaclayton** [comment]
I'm going to close this due to inactivity.
