### ISSUE TITLE
Can't seem to specify multiple --ignore rules

### ISSUE THREAD

**Issue by haasn** [joshuaclayton/unused#87]
I've tried both `unused --search rg --ignore waftools --ignore wscript --ignore gl_headers.h` and `unused --search rg --ignore waftools,wscript,gl_headers.h`.

In both cases, it simply doesn't seem to work. In fact, I seem to see output as if none of the ignore rules were in effect. Specifying only a single `--ignore`, such as just `--ignore waftools`, seems to work.

**Comment by hauleth** [comment]
@joshuaclayton I have encountered today and it was quite irritating.  I have found that I need to rebuild my `tags` file to exclude directories that I want to ignore instead of just ignoring them in `unused`.

**Comment by joshuaclayton** [comment]
@hauleth @haasn sorry about the troubles with this. In the rewrite in Rust I'm working on, I've just added this feature and verified both multiple flags and a comma-delimited list works as expected.

Since I won't be addressing this here, I'll close this out.
