### ISSUE TITLE
When running unused giving me error

### ISSUE THREAD

**Issue by aniketstiwari** [joshuaclayton/unused#90]
When I am trying to run the unused. It is giving me error

There was a problem finding a tags file.

Looked for a 'tags' file in the following directories:

* .git
* tmp
* .

If you're generating a ctags file to a custom location, you can pipe it into unused:
    cat custom/ctags | unused --stdin

You can find out more about Exuberant Ctags here:
    http://ctags.sourceforge.net/

You can read about a good git-based Ctags workflow here:
    http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

**Comment by joshRpowell** [comment]
@aniketstiwari experiencing same issue on a new mac mini. Were you able to find a solution?

**Comment by joshuaclayton** [comment]
Closing this out due to inactivity
