### ISSUE TITLE
Request: support git-grep in addition to ag, rg

### ISSUE THREAD

**Issue by pbrisbin** [joshuaclayton/unused#92]
I'd rather not install something extra. IIUC, ag/rg are (mostly) useful because they automatically consider .gitignore, is that right? If so, using `git grep` should be a "built-in" option provides the same.

**Comment by joshuaclayton** [comment]
This is definitely possible; I'll have to rework how the commands are built, though, since git grep's options are configured differently than how ag/rg are. I'll take a peek and see what I can come up with.

**Comment by joshuaclayton** [comment]
With the rewrite in Rust, this is all done internally rather than shelling out to another tool. Since I won't be tackling this here, I'm closing this issue out.
