### ISSUE TITLE
Should Unused use `-S --pickaxe-regex` instead of `-G`?

### ISSUE THREAD

**Issue by gabebw** [joshuaclayton/unused#95]
From the `git help log` man page:

>-G<regex>
>    Look for differences whose patch text contains added/removed lines that match <regex>.
>
>    To illustrate the difference between -S<regex> --pickaxe-regex and -G<regex>, consider a commit with the following diff in the same file:
>
>        +    return !regexec(regexp, two->ptr, 1, &regmatch, 0);
>        ...
>        -    hit = !regexec(regexp, mf2.ptr, 1, &regmatch, 0);
>
>    While git log -G"regexec\(regexp" will show this commit, git log -S"regexec\(regexp" --pickaxe-regex will not (because the number of occurrences of
>    that string did not change).

It seems like the `-S --pickaxe-regex` behavior is better (where e.g. changing the arguments to a function won't show it in the history for that function).

**Comment by gabebw** [comment]
(Somewhat related-ish to #91.)

**Comment by joshuaclayton** [comment]
Closing this for now, due to a recent rewrite that has other performance implications
